### ISSUE TITLE
SC crashes when run in non-existent directory

### ISSUE THREAD

**Issue by nmoroze** [siliconcompiler/siliconcompiler#1134]
Kind of a funny edge case, but to reproduce in two terminal sessions:

```bash
$ mkdir ~/temp # TERMINAL A
$ cd ~/temp # TERMINAL A
$ rm -rf ~/temp # TERMINAL B
$ sc -version # TERMINAL A
```

You get a traceback like:
```
Traceback (most recent call last):
  File "/home/noah/pyenvs/scdev/bin/sc", line 33, in <module>
    sys.exit(load_entry_point('siliconcompiler', 'console_scripts', 'sc')())
  File "/home/noah/code/siliconcompiler/siliconcompiler/apps/sc.py", line 36, in main
    chip = siliconcompiler.Chip(UNSET_DESIGN)
  File "/home/noah/code/siliconcompiler/siliconcompiler/core.py", line 81, in __init__
    self.cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

should probably handle this a bit more gracefully :)

**Comment by nmoroze** [comment]
Closed by #1158.
