### ISSUE TITLE
No such file or directory: 'openroad'

### ISSUE THREAD

**Issue by suppamax** [siliconcompiler/siliconcompiler#908]
I've installed the docker version of SiliconCompiler using your [Dockerfile](https://github.com/siliconcompiler/siliconcompiler/blob/main/setup/docker/Dockerfile).

When I compile a design (even `heartbeat.v`) I get this error
```
| INFO    | job0    | syn          | 0   | Warnings: 18 unique messages, 113 total
Traceback (most recent call last):
  File "/siliconcompiler/siliconcompiler/core.py", line 3161, in _runtask_safe
    self._runtask(step, index, active, error)
  File "/siliconcompiler/siliconcompiler/core.py", line 3411, in _runtask
    proc = subprocess.run(cmdlist, stdout=PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openroad'
| ERROR   | job0    | floorplan    | 0   | Uncaught exception while running step floorplan.
| ERROR   | job0    | floorplan    | 0   | Halting step 'floorplan' index '0' due to errors.
| ERROR   | job0    | physyn       | 0   | Halting step due to previous error in floorplan0
| ERROR   | job0    | physyn       | 0   | Halting step 'physyn' index '0' due to errors.
| ERROR   | job0    | place        | 0   | Halting step due to previous error in physyn0
| ERROR   | job0    | place        | 0   | Halting step 'place' index '0' due to errors.
| ERROR   | job0    | cts          | 0   | Halting step due to previous error in place0
| ERROR   | job0    | cts          | 0   | Halting step 'cts' index '0' due to errors.
| ERROR   | job0    | route        | 0   | Halting step due to previous error in cts0
| ERROR   | job0    | route        | 0   | Halting step 'route' index '0' due to errors.
| ERROR   | job0    | dfm          | 0   | Halting step due to previous error in route0
| ERROR   | job0    | dfm          | 0   | Halting step 'dfm' index '0' due to errors.
| ERROR   | job0    | export       | 0   | Halting step due to previous error in dfm0
| ERROR   | job0    | export       | 0   | Halting step 'export' index '0' due to errors.
| ERROR   | job0    | ---          | -   | Run() failed, exiting! See previous errors.
```
These are all the openroads I see
```
# find / -iname "openroad*"
/Workarea/sc/build/heartbeat/job0/floorplan/0/openroad.py
/Workarea/sc/build/heartbeat/job0/floorplan/0/__pycache__/openroad.cpython-38.pyc
/siliconcompiler/third_party/pdks/virtual/asap7/pdk/r1p7/apr/openroad_tracks.tcl
/siliconcompiler/third_party/pdks/virtual/asap7/pdk/r1p7/apr/openroad_tapcells.tcl
/siliconcompiler/third_party/tools/openroad
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/src/cmake/openroad.cmake
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/src/OpenRoad.tcl
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/src/OpenRoad.cc
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/src/OpenRoad-py.i
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/src/OpenRoad.i
/siliconcompiler/third_party/tools/openroad/tools/OpenROAD/include/ord/OpenRoad.hh
/siliconcompiler/third_party/tools/openroad/flow/platforms/asap7/openRoad
/siliconcompiler/.git/modules/third_party/tools/openroad
/siliconcompiler/.git/modules/third_party/tools/openroad/modules/tools/OpenROAD
/siliconcompiler/siliconcompiler/tools/openroad
/siliconcompiler/siliconcompiler/tools/openroad/openroad.py
/siliconcompiler/siliconcompiler/tools/openroad/__pycache__/openroad.cpython-38.pyc
/siliconcompiler/_skbuild/linux-x86_64-3.8/cmake-build/third_party/tools/openroad
/siliconcompiler/_skbuild/linux-x86_64-3.8/cmake-build/third_party/tools/openroad/tools/OpenROAD
```

**Comment by suppamax** [comment]
Looks like `libboost-serialization-dev` and `libboost-thread-dev` are required.

**Comment by suppamax** [comment]
See PR #909

**Comment by nmoroze** [comment]
#909 merged, did that fully resolve the issue? If not, feel free to reopen.
